/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/agent/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get History */
        get: operations["get_history_api_agent_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agent/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Status */
        get: operations["get_status_api_agent_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backtest/results/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Results
         * @description Return the current status / results of a previously-submitted backtest.
         */
        get: operations["get_results_api_backtest_results__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backtest/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Backtest
         * @description Enqueue a backtest job.
         *
         *     The endpoint always returns immediately with a freshly-minted
         *     ``run_id``. Callers must poll :func:`get_results` for completion.
         */
        post: operations["run_backtest_api_backtest_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backtest/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Backtest Runs
         * @description List historical backtest runs.
         */
        get: operations["list_backtest_runs_api_backtest_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data/embedding/{kind}/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Embedding */
        get: operations["get_embedding_api_data_embedding__kind___ticker__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data/ohlcv/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ohlcv */
        get: operations["get_ohlcv_api_data_ohlcv__ticker__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/monitoring/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Aggregate health check across Redis, Timescale, broker, kill switch.
         *
         *     Each subsystem's ``health_check`` is independent and may itself fail
         *     (e.g. Redis being unreachable). We catch those exceptions per
         *     subsystem so a single failure does not poison the others.
         */
        get: operations["health_api_monitoring_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/monitoring/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Metrics
         * @description Prometheus scrape endpoint.
         *
         *     The default Prometheus registry is populated by every metric defined
         *     across ``backend/*`` simply via module import (counters and
         *     histograms register themselves on construction). ``generate_latest``
         *     serialises the entire registry in the text exposition format.
         */
        get: operations["metrics_api_monitoring_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Portfolio
         * @description Return the live account snapshot with computed drawdown.
         */
        get: operations["get_portfolio_api_portfolio_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Portfolio History
         * @description Return the historical portfolio equity.
         */
        get: operations["get_portfolio_history_api_portfolio_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/risk/kill-switch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Kill Switch State */
        get: operations["get_kill_switch_state_api_risk_kill_switch_get"];
        put?: never;
        /** Set Kill Switch */
        post: operations["set_kill_switch_api_risk_kill_switch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/arena/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Run
         * @description Enqueue an arena run; return immediately with the new run_id.
         */
        post: operations["start_run_arena_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/arena/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_arena_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/arena/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_arena_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/arena/runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Run
         * @description Set a cooperative-cancel flag in Redis. The worker polls it.
         */
        post: operations["cancel_run_arena_runs__run_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/arena/runs/{run_id}/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Decisions */
        get: operations["get_decisions_arena_runs__run_id__decisions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/arena/runs/{run_id}/divergences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Divergences */
        get: operations["get_divergences_arena_runs__run_id__divergences_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/arena/runs/{run_id}/explanations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Explanations */
        get: operations["get_explanations_arena_runs__run_id__explanations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/arena/runs/{run_id}/pairs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Pairs */
        get: operations["get_pairs_arena_runs__run_id__pairs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/arena/runs/{run_id}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Summary
         * @description Look up a cached :class:`RunSummary` written by the worker.
         */
        get: operations["get_summary_arena_runs__run_id__summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActionKind
         * @enum {string}
         */
        ActionKind: "BUY" | "SELL" | "HOLD" | "REDUCE" | "INCREASE";
        /**
         * AgentStatusResponse
         * @description Snapshot of the live agent surfaced to the dashboard.
         */
        AgentStatusResponse: {
            /** Attention Weights */
            attention_weights?: number[] | null;
            /**
             * Consecutive Vetoes
             * @default 0
             */
            consecutive_vetoes: number;
            /** Current Action */
            current_action: number;
            /** Gate Active */
            gate_active: boolean;
            /**
             * Has Action
             * @default false
             */
            has_action: boolean;
            /**
             * Last Update
             * Format: date-time
             */
            last_update: string;
            /** Uncertainty */
            uncertainty: number;
        };
        /** ArenaRunCreatedResponse */
        ArenaRunCreatedResponse: {
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** @default PENDING */
            status: components["schemas"]["ArenaRunStatus"];
        };
        /**
         * ArenaRunMetadata
         * @description The control record for an entire arena run.
         */
        ArenaRunMetadata: {
            /** Completed At */
            completed_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * End Date
             * Format: date-time
             */
            end_date: string;
            /** Failure Reason */
            failure_reason?: string | null;
            /** Mc Seeds */
            mc_seeds: number[];
            /** N Trajectories */
            n_trajectories: number;
            /**
             * Playback Multiplier
             * @default 1
             */
            playback_multiplier: number;
            /**
             * Run Id
             * Format: uuid
             */
            run_id?: string;
            /**
             * Start Date
             * Format: date-time
             */
            start_date: string;
            /** @default PENDING */
            status: components["schemas"]["ArenaRunStatus"];
            /** Ticker */
            ticker: string;
        };
        /**
         * ArenaRunRequest
         * @description POST /arena/run body — minimal control surface.
         */
        ArenaRunRequest: {
            /**
             * End Date
             * Format: date-time
             */
            end_date: string;
            /** Mc Seeds */
            mc_seeds?: number[] | null;
            /**
             * N Trajectories
             * @default 8
             */
            n_trajectories: number;
            /**
             * Playback Multiplier
             * @default 1
             */
            playback_multiplier: number;
            /**
             * Start Date
             * Format: date-time
             */
            start_date: string;
            /** Ticker */
            ticker: string;
        };
        /**
         * ArenaRunStatus
         * @enum {string}
         */
        ArenaRunStatus: "PENDING" | "RUNNING" | "COMPLETED" | "FAILED" | "CANCELLED";
        /**
         * ArenaSettings
         * @description Runtime configuration for the Spartan Arena subsystem.
         */
        ArenaSettings: {
            /**
             * Artifact Dir
             * Format: path
             * @default artifacts/arena
             */
            artifact_dir: string;
            /**
             * Default Playback Multiplier
             * @default 1
             */
            default_playback_multiplier: number;
            /**
             * Enable Run Summarizer Llm
             * @default false
             */
            enable_run_summarizer_llm: boolean;
            /** Run Summarizer Model Path */
            run_summarizer_model_path?: string | null;
        };
        /**
         * AttributionPayload
         * @description All attribution signals extracted at a single decision step.
         */
        AttributionPayload: {
            cross_modal: components["schemas"]["CrossModalWeights"];
            /** Gat Edges Top */
            gat_edges_top?: components["schemas"]["GATEdgeCoefficient"][];
            /** Llm Top Tokens */
            llm_top_tokens?: [
                string,
                number
            ][] | null;
            /** Tft Vsn Top */
            tft_vsn_top?: components["schemas"]["VSNWeight"][];
        };
        /**
         * BacktestRequest
         * @description Submit a backtest job to the worker queue.
         */
        BacktestRequest: {
            /**
             * End
             * Format: date-time
             */
            end: string;
            /**
             * Initial Capital
             * @default 100000
             */
            initial_capital: number;
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /** Tickers */
            tickers: string[];
        };
        /**
         * BacktestResultResponse
         * @description Async result polling. ``status`` walks pending → running → completed.
         */
        BacktestResultResponse: {
            /** Failure Reason */
            failure_reason?: string | null;
            /** Max Drawdown */
            max_drawdown?: number | null;
            /** Run Id */
            run_id: string;
            /** Sharpe */
            sharpe?: number | null;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "running" | "completed" | "failed";
            /** Total Return */
            total_return?: number | null;
        };
        /**
         * CounterfactualPair
         * @description A training-grade triplet derived from a DivergencePoint.
         *
         *     Written to disk as JSONL and consumed by feedback/replay_buffer_writer.py
         *     to build BC datasets for the next training run.
         */
        CounterfactualPair: {
            /** Bad Action Vector */
            bad_action_vector: number[];
            /** Bad Outcome Sharpe */
            bad_outcome_sharpe: number;
            /**
             * Confidence Score
             * @description How confident we are that this pair represents a real pivot, derived from sharpe_delta and action_l2_distance.
             */
            confidence_score: number;
            /** Divergence Step Index */
            divergence_step_index: number;
            /** Good Action Vector */
            good_action_vector: number[];
            /** Good Outcome Sharpe */
            good_outcome_sharpe: number;
            /**
             * Pair Id
             * Format: uuid
             */
            pair_id?: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Sim Timestamp
             * Format: date-time
             */
            sim_timestamp: string;
            /** State Artifact Path */
            state_artifact_path: string;
        };
        /**
         * CrossModalWeights
         * @description Weights assigned by the Deep Fusion Nexus to each modality.
         *
         *     The three weights must sum to 1.0 (the attention block applies softmax).
         */
        CrossModalWeights: {
            /** Graph */
            graph: number;
            /** News */
            news: number;
            /** Price */
            price: number;
        };
        /**
         * DecisionRecord
         * @description One decision taken by the agent in one trajectory at one timestep.
         *
         *     Persisted to TimescaleDB table `arena_decision_records`. The 224-d
         *     super-state vector is stored out-of-band in the artifact directory,
         *     not in the database row; only its path is kept here.
         */
        DecisionRecord: {
            action_kind: components["schemas"]["ActionKind"];
            /** Action Vector */
            action_vector: number[];
            attribution: components["schemas"]["AttributionPayload"];
            /** Confidence */
            confidence: number;
            /** Mc Seed */
            mc_seed: number;
            /** Ohlcv */
            ohlcv: {
                [key: string]: number;
            };
            /** Realized Reward */
            realized_reward?: number | null;
            /**
             * Record Id
             * Format: uuid
             */
            record_id?: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Sim Timestamp
             * Format: date-time
             */
            sim_timestamp: string;
            /** State Artifact Path */
            state_artifact_path: string;
            /** Step Index */
            step_index: number;
            /** Ticker */
            ticker: string;
            /** Trajectory Id */
            trajectory_id: number;
            /** Uncertainty */
            uncertainty: number;
            /**
             * Wall Timestamp
             * Format: date-time
             */
            wall_timestamp: string;
        };
        /**
         * DivergencePoint
         * @description A step where trajectories diverged AND subsequent outcomes differed.
         */
        DivergencePoint: {
            /** Action L2 Distance */
            action_l2_distance: number;
            /** Best Action Vector */
            best_action_vector: number[];
            /** Best Subsequent Sharpe */
            best_subsequent_sharpe: number;
            /** Best Trajectory Id */
            best_trajectory_id: number;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Sharpe Delta */
            sharpe_delta: number;
            /**
             * Sim Timestamp
             * Format: date-time
             */
            sim_timestamp: string;
            /** Step Index */
            step_index: number;
            /** Worst Action Vector */
            worst_action_vector: number[];
            /** Worst Subsequent Sharpe */
            worst_subsequent_sharpe: number;
            /** Worst Trajectory Id */
            worst_trajectory_id: number;
        };
        /** EquityPoint */
        EquityPoint: {
            /** Benchmark */
            benchmark?: number | null;
            /** Equity */
            equity: number;
            /**
             * Time
             * Format: date-time
             */
            time: string;
        };
        /**
         * GATEdgeCoefficient
         * @description One edge of the GATv2 graph at this decision step.
         */
        GATEdgeCoefficient: {
            /** Coefficient */
            coefficient: number;
            /** Source Ticker */
            source_ticker: string;
            /** Target Ticker */
            target_ticker: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Top-level health response returned by ``GET /api/monitoring/health``.
         *
         *     The ``components`` field is a free-form mapping of subsystem-name to
         *     subsystem-specific health dictionary. Subsystems known to the API:
         *     ``redis``, ``timescale``, ``broker``, ``kill_switch``.
         *
         *     The aggregate ``status`` is derived as follows:
         *         * "ok"       — every component reports ``connected = True`` AND
         *                         the kill switch is "NORMAL".
         *         * "degraded" — at least one component is unreachable OR the
         *                         kill switch is "CLOSE_ONLY".
         *         * "down"     — the kill switch is "LIQUIDATE_ALL".
         */
        HealthResponse: {
            /** Components */
            components: {
                [key: string]: {
                    [key: string]: unknown;
                };
            };
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded" | "down";
        };
        /** KillSwitchRequest */
        KillSwitchRequest: {
            /**
             * Reason
             * @default
             */
            reason: string;
            /**
             * State
             * @enum {string}
             */
            state: "NORMAL" | "CLOSE_ONLY" | "LIQUIDATE_ALL";
        };
        /** KillSwitchResponse */
        KillSwitchResponse: {
            /**
             * Set At
             * Format: date-time
             */
            set_at: string;
            /** State */
            state: string;
        };
        /**
         * OHLCVResponse
         * @description A single OHLCV bar as returned by ``GET /api/data/ohlcv/{ticker}``.
         */
        OHLCVResponse: {
            /** Close */
            close: number;
            /** High */
            high: number;
            /** Low */
            low: number;
            /** Open */
            open: number;
            /**
             * Time
             * Format: date-time
             */
            time: string;
            /** Volume */
            volume: number;
        };
        /** PortfolioHistoryResponse */
        PortfolioHistoryResponse: {
            /** History */
            history: components["schemas"]["EquityPoint"][];
        };
        /**
         * PortfolioResponse
         * @description Account-level summary returned by ``GET /api/portfolio``.
         *
         *     ``drawdown_pct`` is the *peak-to-trough* drawdown expressed as a
         *     positive fraction in [0, 1]. Computed by the API rather than the
         *     broker because the broker (especially the live Alpaca adapter) does
         *     not track peak equity natively. We persist the peak in Redis under
         *     ``portfolio:peak_equity`` and update it on every ``GET`` call.
         */
        PortfolioResponse: {
            /** Buying Power */
            buying_power: number;
            /** Cash */
            cash: number;
            /** Drawdown Pct */
            drawdown_pct: number;
            /** Equity */
            equity: number;
            /** Peak Equity */
            peak_equity: number;
            /** Positions */
            positions: components["schemas"]["PositionResponse"][];
        };
        /**
         * PositionResponse
         * @description A single open position. Mirrors :class:`Position` from the broker.
         */
        PositionResponse: {
            /** Avg Entry Price */
            avg_entry_price: number;
            /** Market Value */
            market_value: number;
            /** Qty */
            qty: number;
            /** Ticker */
            ticker: string;
            /** Unrealized Pnl */
            unrealized_pnl: number;
        };
        /**
         * RunSummary
         * @description End-of-run narrative produced by xai/run_summarizer.py.
         */
        RunSummary: {
            /** Best Trajectory Id */
            best_trajectory_id: number;
            /** N Divergences */
            n_divergences: number;
            /** N Pivotal Divergences */
            n_pivotal_divergences: number;
            /** Narrative */
            narrative: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Summary Method
             * @enum {string}
             */
            summary_method: "template" | "slm";
            /** Worst Trajectory Id */
            worst_trajectory_id: number;
        };
        /** Settings */
        Settings: {
            /**
             * Agent Tick Interval Seconds
             * @default 1
             */
            AGENT_TICK_INTERVAL_SECONDS: number;
            /**
             * Allow Random Models
             * @default false
             */
            ALLOW_RANDOM_MODELS: boolean;
            /**
             * Allow Synthetic Simulation Fallback
             * @default false
             */
            ALLOW_SYNTHETIC_SIMULATION_FALLBACK: boolean;
            /**
             * Alpaca Api Key
             * @default
             */
            ALPACA_API_KEY: string;
            /**
             * Alpaca Paper
             * @default true
             */
            ALPACA_PAPER: boolean;
            /**
             * Alpaca Secret Key
             * @default
             */
            ALPACA_SECRET_KEY: string;
            /**
             * Api Key
             * @default
             */
            API_KEY: string;
            /**
             * Arena Synthetic Steps
             * @default 240
             */
            ARENA_SYNTHETIC_STEPS: number;
            /**
             * Arena Worker Poll Seconds
             * @default 1
             */
            ARENA_WORKER_POLL_SECONDS: number;
            /**
             * Backtest Synthetic Steps
             * @default 252
             */
            BACKTEST_SYNTHETIC_STEPS: number;
            /**
             * Backtest Worker Poll Seconds
             * @default 1
             */
            BACKTEST_WORKER_POLL_SECONDS: number;
            /**
             * Broker Mode
             * @default paper
             * @enum {string}
             */
            BROKER_MODE: "alpaca" | "paper";
            /**
             * Collector Heartbeat S
             * @default 30
             */
            COLLECTOR_HEARTBEAT_S: number;
            /**
             * Collector Max Backoff S
             * @default 60
             */
            COLLECTOR_MAX_BACKOFF_S: number;
            /** Cors Origins */
            CORS_ORIGINS?: string[];
            /**
             * Environment
             * @default development
             * @enum {string}
             */
            ENVIRONMENT: "development" | "staging" | "production";
            /**
             * Feature Store Batch Size
             * @default 64
             */
            FEATURE_STORE_BATCH_SIZE: number;
            /**
             * Feature Store Num Workers
             * @default 4
             */
            FEATURE_STORE_NUM_WORKERS: number;
            /**
             * Graph Inference Interval Seconds
             * @default 86400
             */
            GRAPH_INFERENCE_INTERVAL_SECONDS: number;
            /**
             * Ingestion Backpressure Factor
             * @default 2
             */
            INGESTION_BACKPRESSURE_FACTOR: number;
            /**
             * Ingestion Batch Size
             * @default 1000
             */
            INGESTION_BATCH_SIZE: number;
            /**
             * Ingestion Flush Interval S
             * @default 5
             */
            INGESTION_FLUSH_INTERVAL_S: number;
            /**
             * Ingestion Max Retries
             * @default 3
             */
            INGESTION_MAX_RETRIES: number;
            /**
             * Initial Capital
             * @default 100000
             */
            INITIAL_CAPITAL: number;
            /** Live Tickers */
            LIVE_TICKERS?: string[];
            /**
             * Log Level
             * @default INFO
             */
            LOG_LEVEL: string;
            /**
             * Max Drawdown Limit
             * @default 0.2
             */
            MAX_DRAWDOWN_LIMIT: number;
            /**
             * Mlflow Backtest Experiment Name
             * @default lumina_v3_backtests
             */
            MLFLOW_BACKTEST_EXPERIMENT_NAME: string;
            /**
             * Mlflow Experiment Name
             * @default lumina_v3_arena
             */
            MLFLOW_EXPERIMENT_NAME: string;
            /**
             * Mlflow Tracking Uri
             * @default http://mlflow:5000
             */
            MLFLOW_TRACKING_URI: string;
            /**
             * Newsapi Key
             * @default
             */
            NEWSAPI_KEY: string;
            /**
             * News Poll Interval Seconds
             * @default 60
             */
            NEWS_POLL_INTERVAL_SECONDS: number;
            /**
             * Polygon Api Key
             * @default
             */
            POLYGON_API_KEY: string;
            /**
             * Polygon Rest Url
             * @default https://api.polygon.io
             */
            POLYGON_REST_URL: string;
            /**
             * Polygon Ws Url
             * @default wss://socket.polygon.io/stocks
             */
            POLYGON_WS_URL: string;
            /**
             * Redis Max Connections
             * @default 50
             */
            REDIS_MAX_CONNECTIONS: number;
            /**
             * Redis Url
             * @default redis://localhost:6379/0
             */
            REDIS_URL: string;
            /**
             * Synthetic Feed Bootstrap Days
             * @default 90
             */
            SYNTHETIC_FEED_BOOTSTRAP_DAYS: number;
            /**
             * Synthetic Feed News Interval Seconds
             * @default 30
             */
            SYNTHETIC_FEED_NEWS_INTERVAL_SECONDS: number;
            /**
             * Synthetic Feed Seed
             * @default 7
             */
            SYNTHETIC_FEED_SEED: number;
            /**
             * Synthetic Feed Tick Interval Seconds
             * @default 1
             */
            SYNTHETIC_FEED_TICK_INTERVAL_SECONDS: number;
            /**
             * Timescale Pool Max
             * @default 20
             */
            TIMESCALE_POOL_MAX: number;
            /**
             * Timescale Pool Min
             * @default 5
             */
            TIMESCALE_POOL_MIN: number;
            /**
             * Timescale Url
             * @default postgresql://lumina:lumina@localhost:5432/lumina
             */
            TIMESCALE_URL: string;
            /**
             * Uncertainty Threshold
             * @default 0.85
             */
            UNCERTAINTY_THRESHOLD: number;
            arena?: components["schemas"]["ArenaSettings"];
        };
        /**
         * StepExplanation
         * @description A rendered terminal-style explanation of a single DecisionRecord.
         *
         *     Produced by xai/step_explainer.py. The `text` field is the formatted
         *     multi-line block; `tags` is a structured index for search/filter.
         */
        StepExplanation: {
            /**
             * Record Id
             * Format: uuid
             */
            record_id: string;
            /** Tags */
            tags: ("overbought" | "oversold" | "panic" | "contagion" | "low_confidence" | "kill_switch_near")[];
            /** Text */
            text: string;
        };
        /**
         * VSNWeight
         * @description One entry of the Temporal Fusion Transformer's Variable Selection Network.
         */
        VSNWeight: {
            /**
             * Feature
             * @description Feature name, e.g. 'rsi_14', 'volume', 'close'.
             */
            feature: string;
            /**
             * State
             * @description Human label, e.g. 'overbought', 'neutral'.
             */
            state: string;
            /** Weight */
            weight: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_history_api_agent_history_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_status_api_agent_status_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_results_api_backtest_results__run_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestResultResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_backtest_api_backtest_run_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BacktestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestResultResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_backtest_runs_api_backtest_runs_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestResultResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_embedding_api_data_embedding__kind___ticker__get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                kind: "price" | "semantic" | "graph";
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ohlcv_api_data_ohlcv__ticker__get: {
        parameters: {
            query: {
                start: string;
                end: string;
            };
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OHLCVResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_monitoring_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["Settings"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    metrics_api_monitoring_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_portfolio_api_portfolio_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["Settings"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_portfolio_history_api_portfolio_history_get: {
        parameters: {
            query?: {
                range?: string;
            };
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioHistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_kill_switch_state_api_risk_kill_switch_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KillSwitchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_kill_switch_api_risk_kill_switch_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KillSwitchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KillSwitchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_run_arena_run_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArenaRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArenaRunCreatedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_arena_runs_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArenaRunMetadata"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_arena_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArenaRunMetadata"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_run_arena_runs__run_id__cancel_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_decisions_arena_runs__run_id__decisions_get: {
        parameters: {
            query?: {
                trajectory_id?: number | null;
                limit?: number;
                offset?: number;
            };
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionRecord"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_divergences_arena_runs__run_id__divergences_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DivergencePoint"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_explanations_arena_runs__run_id__explanations_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StepExplanation"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_pairs_arena_runs__run_id__pairs_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CounterfactualPair"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_summary_arena_runs__run_id__summary_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
